export const SET_ALL_COMPANY_TICKERS_AND_NAMES = "SET_ALL_COMPANY_TICKERS_AND_NAMES"
export const SELECT_TARGET_COMPANY = "SELECT_TARGET_COMPANY"
export const SET_CHART_INSTANCE = "SET_CHART_INSTANCE"
export const SELECT_TIME_RANGE = "SELECT_TIME_RANGE"